// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftpopnbnhmgxjyfmojnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0cG9wbmJuaG1neGp5Zm1vam5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NDMwMzUsImV4cCI6MjA1NTUxOTAzNX0.epZ26eigfcjwhUdNd8AT-TYq-RWr0tGnZOKpRfRlH-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);